default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: Loveda1234
  host: localhost

development:
  <<: *default
  database: hospital_portal_development

test:
  <<: *default
  database: hospital_portal_test

production:
  <<: *default
  database: hospital_portal_production
  username: hospital_user
  password: <%= ENV['HOSPITAL_PORTAL_DATABASE_PASSWORD'] %>